CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000

CONFIG_ZMK_BATTERY_REPORTING=y

CONFIG_ZMK_NON_LIPO_BATTERY_MANAGEMENT=y

# このモジュールが計算した%をZMKの電池残量として使う
CONFIG_ZMK_BATTERY_REPORTING_FETCH_MODE_STATE_OF_CHARGE=y

# XIAO nRF52840内蔵の分圧後電圧を読む前提の値
# アルカリ単四1本: 約1.0V〜1.5V → ADC上では約338mV〜507mV
CONFIG_ZMK_NON_LIPO_MIN_MV=338
CONFIG_ZMK_NON_LIPO_MAX_MV=507
CONFIG_ZMK_NON_LIPO_LOW_MV=320

# まずは勝手にスリープしないように無効化
CONFIG_ZMK_NON_LIPO_ADV_SLEEP_TIMEOUT=0
